version: '3'

services:

  npm:
    image: node:12-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run start

  web:
    build: .
    volumes:
      - ./:/var/www/localhost
      - ./web/:/var/www/localhost/htdocs
    ports:
      - 8881:80
